+---
title: "Exploratory Data Analysis"
author: "Lissa Harrop, Katrina Watkins, Ricky Loo and Max Tan"
date: "16 August 2022"
classoption: 12pt
  
header-includes:
  - \usepackage{newpxtext,eulerpx}
  - \usepackage{bm,bbm}
  - \usepackage{float}

output: bookdown::pdf_document2

#link-citations: yes
#bibliography: references.bib
#citation_package: biblatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(300521444, kind="Mersenne-Twister") #Mixture of all our ID numbers
require(ggplot2)
require(ggthemes)
require(extrafont)
require(booktabs)
require(GGally)
require(ggExtra)
require(xtable)
require(moments)
require(ggcorrplot)
require(fitdistrplus)
require(reshape2)
```

```{r, echo=FALSE}
lovoo <- read.csv("C:/Users/L Harrop/OneDrive/Study/STAT_394/Project/Group-Project/Data/CSV/lovoo_v3_users_api-results.csv")
# Need to set a relative path!
lovoo <- data.frame(lovoo)
lovoo <- lovoo[, c("age", "counts_pictures", "counts_profileVisits", "counts_kisses", "distance", "country", "isVip")]
lovoo
```
```{r}
lovoo$country <- as.factor(lovoo$country)
lovoo$isVip <- as.factor(lovoo$isVip)
summary(lovoo)
```
